services:
           
    mlbot:
        image: mlbot
        container_name: mlbot
        env_file: secrets.env
        ports:
          - "0.0.0.0:5000:5000"
        networks:
          local:
          mlbot:
networks:
  local:
  mlbot:
      
